---
version: '2'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - 'docker-postgres:/var/lib/postgresql/data'
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - 'docker-redis:/var/lib/redis/data'
  app:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bundle exec puma -C config/puma.rb
    env_file:
      - .docker.env
    links:
      - postgres
      -redis
volumes:
  docker-postgres:
  docker-redis:
